### ISSUE TITLE
Factory Functionality Not Available

### ISSUE THREAD

**Issue by jmartin111** [TotomInc/totominc.github.io#25]
Hi TotomInc,

I really enjoy this game but it seems the factory functionality is not working (not ready?). The current version of the game implies that the factory is available for those players with 200K exp. I currently have 2.85T exp. Looking forward to seeing this feature in the future!

**Comment by Latteralus** [comment]
Hello Martin,

We're working on this feature as I type. After we do some bug hunting and balancing we'll be ready for a release. We're taking our time as we don't want to rush it and something go wrong. 

I hope you're enjoying Blackmarket as much as we enjoy making it!
 - Latteralus
