### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by Aquaeyes** [TotomInc/totominc.github.io#31]
Hello, I found a few grammatical mistakes in the tutorial, so I made rectified versions, if you don't mind that is.

Tutorial.js
Line 21: "Water costs 20 hydrogen and 10 oxygen : it's cost doesn't increase!<br> " +
Line 27: string: "Nice, your planet now has some <b>water</b>, but this water is cold.<br> " +
Line 36: "Your planet also needs an <b>atmosphere</b>.<br> " +
Line 37: "Without an atmosphere, the cells can not live.<br> " +
Line 45: "Each cell generates <b>0.1 meat/sec</b>. " + g.t.spacer +

Thanks!
P.S, I looked at the code, and it's amazingly good, you are a great coder!

**Comment by TotomInc** [comment]
Thanks for reporting these grammatical mistakes, I'm not a native English speaker! :)

I'm working on the new version of Universe-God (which is currently no available on my GitHub), so stay tuned!
