### ISSUE TITLE
Problem with the fade in incremental RPG

### ISSUE THREAD

**Issue by cahema** [TotomInc/totominc.github.io#32]
When i click in a menu the fade is OVER the menu so i can't click anything

**Comment by NewbiZ** [comment]
I can confirm same behavior on chrome.

**Comment by TotomInc** [comment]
Thanks for reporring the issue, its just a z-index problem and should be fixed ASAP.

I will see what I can add to the game! :)

**Comment by TotomInc** [comment]
Fixed.
