### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by MasterGroosha** [TotomInc/totominc.github.io#37]
What Licence does your project have? What about forking and changing code? Any limitations?

**Comment by TotomInc** [comment]
All my projects in totominc.github.io repo have the MIT license. [Here what you can or can't do with it.](https://opensource.org/licenses/MIT)

**Comment by MasterGroosha** [comment]
Thank you for the info! 
Could you please answer one more question? 
`The above copyright notice and this permission notice shall be included`... what should I do if I'm going to use a modified version of your game in an standalone application?

**Comment by TotomInc** [comment]
If you plan to make a derivation of one of my game, you should put a credit somewhere on your application. Something like "original idea from TotomInc".

**Comment by MasterGroosha** [comment]
Got it, will do, thanks!
